/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.pierlluigi.patrones.cliente;

import com.pierluigi.patrones.memento.Caretaker;
import com.pierluigi.patrones.memento.Texto;

/**
 *
 * @author pier
 */
public class clienteMemento extends javax.swing.JPanel {

    /**
     * Creates new form clienteMemento
     */
    Texto texto;
    Caretaker caretaker;
    public clienteMemento() {
        initComponents();
        texto = new Texto();
        caretaker = new Caretaker();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Atras = new javax.swing.JButton();
        Adelante = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textoDoc = new javax.swing.JTextArea();
        crearMemento = new javax.swing.JButton();

        Atras.setText("Atras");
        Atras.setName("atras"); // NOI18N
        Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasActionPerformed(evt);
            }
        });

        Adelante.setText("Adelante");
        Adelante.setName("adelante"); // NOI18N
        Adelante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdelanteActionPerformed(evt);
            }
        });

        textoDoc.setColumns(20);
        textoDoc.setRows(5);
        textoDoc.setName("documento"); // NOI18N
        jScrollPane1.setViewportView(textoDoc);

        crearMemento.setText("Crear Memento");
        crearMemento.setName("crear"); // NOI18N
        crearMemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearMementoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(crearMemento))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(Atras)
                        .addGap(18, 18, 18)
                        .addComponent(Adelante)))
                .addGap(65, 65, 65))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Atras)
                    .addComponent(Adelante))
                .addGap(33, 33, 33)
                .addComponent(crearMemento)
                .addGap(40, 40, 40))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void crearMementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearMementoActionPerformed
        texto.setTexto(textoDoc.getText());
        caretaker.backup(texto.createMemento());
    }//GEN-LAST:event_crearMementoActionPerformed

    private void AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasActionPerformed
        texto.setTextoFromMemento(caretaker.atras());
        textoDoc.setText(texto.getTexto());
    }//GEN-LAST:event_AtrasActionPerformed

    private void AdelanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdelanteActionPerformed
        texto.setTextoFromMemento(caretaker.delante());
        textoDoc.setText(texto.getTexto());
    }//GEN-LAST:event_AdelanteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Adelante;
    private javax.swing.JButton Atras;
    private javax.swing.JButton crearMemento;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textoDoc;
    // End of variables declaration//GEN-END:variables
}
