/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.pierlluigi.patrones.cliente;

import com.pierluigi.patrones.plantilla.Serie;
import com.pierluigi.patrones.plantilla.SerieA;
import com.pierluigi.patrones.plantilla.SerieB;

/**
 *
 * @author pier
 */
public class clientePlantilla extends javax.swing.JPanel {

    /**
     * Creates new form clientePlantilla
     */
    Serie serie;
    public clientePlantilla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        valor = new javax.swing.JTextField();
        serieA = new javax.swing.JButton();
        serieB = new javax.swing.JButton();
        resultado = new javax.swing.JLabel();

        valor.setName("valor"); // NOI18N

        serieA.setText("Serie A");
        serieA.setName("serieA"); // NOI18N
        serieA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serieAActionPerformed(evt);
            }
        });

        serieB.setText("Serie B");
        serieB.setName("serieB"); // NOI18N
        serieB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serieBActionPerformed(evt);
            }
        });

        resultado.setName("resultado"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(serieA)
                        .addGap(38, 38, 38)
                        .addComponent(serieB))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(valor, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serieA)
                    .addComponent(serieB))
                .addGap(29, 29, 29)
                .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(141, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void serieBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serieBActionPerformed
        serie = new SerieB();
        serie.setValor(Integer.parseInt(valor.getText()));
        resultado.setText(serie.metodoPlantilla());
    }//GEN-LAST:event_serieBActionPerformed

    private void serieAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serieAActionPerformed
        serie = new SerieA();
        serie.setValor(Integer.parseInt(valor.getText()));
        resultado.setText(serie.metodoPlantilla());
    }//GEN-LAST:event_serieAActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel resultado;
    private javax.swing.JButton serieA;
    private javax.swing.JButton serieB;
    private javax.swing.JTextField valor;
    // End of variables declaration//GEN-END:variables
}
